# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 16:38
from __future__ import unicode_literals

import basic_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10, validators=[basic_app.models.validate_number])),
                ('pincode', models.CharField(max_length=6, validators=[basic_app.models.validate_number1])),
                ('test', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
