# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt_doctor',
            name='sp_name',
        ),
        migrations.RemoveField(
            model_name='mst_patient',
            name='sp_name',
        ),
    ]
